Welke vragen hebben gebruikers? Wat willen we communiceren?

- hoe houdt de applicatie bij wie ik heb ontmoet?
- wanneer wordt een ontmoeting als risicovol gezien?
- waar wordt deze data opgeslagen?
- hoe lang wordt deze data opgeslagen?
- wie heeft er toegang tot deze data?
- wanneer wordt deze data gedeeld?
- hoe wordt anonimiteit gegarandeerd?
- gebruikt bluetooth veel batterij?
- gebruikt de app veel data?
- wordt mijn locatie opgeslagen?
- wanneer krijg ik een notificatie?
- wat krijgt ik bij deze notificatie te horen? (dag)
- wat krijg ik bij deze notificatie niet te horen (persoon, tijdstip, locatie)
- wat zal het advies zijn na een risicovolle ontmoeting?
- hoe kan ik mijzelf laten testen?
- hoe wordt een testuitslag gecommuniceerd?
- hoe kan ik mijzelf als positief getest melden?
- wat krijgen mijn contacten te horen wanneer ik positief ben getest?
- hoe kan ik de applicatie delen met vrienden en familie?
- waarschuwt de app wanneer deze stopt met werken? (i.e. data, bluetooth)
- hoe geef ik de juiste permissies?
- werkt de applicatie in de achtergrond?
- hoe accuraat is bluetooth? 
- kan ik de applicatie tijdelijk pauzeren?
- kunnen anderen aan mijn applicatie zien dat ik een risicovolle ontmoeting heb gehad?
- kan ik alle informatie verwijderen?
